language: python
os:
  - linux
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r dev-requirements.txt
  - pip install coveralls
script:
  - python -m unittest discover
after_success:
  - coveralls