__title__ = 'timewalk'
__description__ = 'core package for timewalk, a coding stats tracking software.'
__url__ = 'https://github.com/desmondlzy/timewalk'
__version_info__ = ('0', '0', '2')
__version__ = '.'.join(__version_info__)
__author__ = 'Desmond Zhenyuan Liu'
__author_email__ = 'desmondzyliu@gmail.com'
__license__ = 'BSD'
__copyright__ = 'Copyright 2020 Zhenyuan Liu'
